// SPDX-FileCopyrightText: 2024-2026 Benjamin Jörissen
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Chapter-collapse model comparison on Chapter 1 (L1=9c3e2dac…) against the
// Opus 4.7 goldstandard at docs/experiments/chapter1-opus-collapse.json.
//
// Setup expectation:
//   - All 7 L3 section-collapse memos for Chapter 1 are present in DB
//     (Opus-generated by the chapter-1-pipeline run on 2026-05-01).
//   - The L1 chapter-collapse memo for Chapter 1 may or may not be present;
//     this driver removes it before each model and re-creates it with the
//     model under test.
//
// Per model:
//   1. delete existing [kontextualisierend/chapter/graph] memo for L1
//   2. runChapterCollapse with modelOverride
//   3. dump JSON to docs/experiments/chapter1-compare-<key>.json
//
// Final cleanup: delete the last model's chapter memo so the DB chapter-level
// state is "no chapter memo" — the user can re-run scripts/run-chapter-collapse.ts
// (which uses the ai-settings.json default = Opus) to restore the Opus baseline,
// or just compare via the JSON dumps without a DB restore.
//
// Run from repo root:   npx tsx scripts/compare-models-chapter-collapse.ts

import { writeFileSync, mkdirSync } from 'node:fs';
import { runChapterCollapse } from '../src/lib/server/ai/hermeneutic/chapter-collapse.ts';
import { pool, query } from '../src/lib/server/db/index.ts';
import type { Provider } from '../src/lib/server/ai/client.ts';

const CASE_ID = 'aa23d66e-9cd8-4583-9d14-6120dc343b10';
const USER_ID = 'dac6ac05-bdab-4d68-a4fa-3eab0b40cc2b';
// Chapter 1: "Schule – Kultur – Globalität – Lehrkräftebildung" (74 ¶, 7 L3 subchapters).
const L1_HEADING_ID = '9c3e2dac-a9bb-4cb5-8a6d-19a87c086341';

interface ModelCfg { key: string; provider: Provider; model: string; }

// Start with DS4 only. Opus baseline already exists at chapter1-opus-collapse.json
// (legacy schema: { result, tokens, aggregation_level, wall } — render-script
// normalises). Add Sonnet/Mistral here later if useful.
const MODELS: ModelCfg[] = [
	{ key: 'deepseek-v4-pro', provider: 'openrouter', model: 'deepseek/deepseek-v4-pro' },
];

const RETRYABLE_STATUS = new Set([429, 502, 503, 504, 524, 408]);

async function withRetry<T>(label: string, fn: () => Promise<T>, attempts = 3): Promise<T> {
	let lastErr: unknown;
	for (let i = 1; i <= attempts; i++) {
		try { return await fn(); }
		catch (err) {
			lastErr = err;
			const status = (err as { status?: number })?.status;
			const retryable = status !== undefined && RETRYABLE_STATUS.has(status);
			if (!retryable || i === attempts) throw err;
			const wait = 5000 * i ** 2;
			console.log(`  ↻ ${label}: ${status} on attempt ${i}/${attempts}, retry in ${wait/1000}s`);
			await new Promise(r => setTimeout(r, wait));
		}
	}
	throw lastErr;
}

async function deleteChapterMemo(l1HeadingId: string) {
	// Find graph-fed kontextualisierend chapter memos for this L1 and DELETE.
	// FK cascades remove memo_content + appearances.
	await query(
		`DELETE FROM namings WHERE id IN (
		   SELECT n.id FROM namings n
		   JOIN memo_content mc ON mc.naming_id = n.id
		   WHERE n.inscription LIKE '[kontextualisierend/chapter/graph]%'
		     AND mc.scope_element_id = $1
		     AND mc.scope_level = 'chapter')`,
		[l1HeadingId]
	);
}

const OUT_DIR = 'docs/experiments';
mkdirSync(OUT_DIR, { recursive: true });

interface ChapterRecord {
	model: ModelCfg;
	wall_seconds: number;
	tokens: { input: number; output: number; cacheCreation: number; cacheRead: number; total: number };
	aggregation_level: 1 | 2 | 3;
	input_mode: 'paragraphs' | 'subchapter-memos';
	input_count: number;
	result: unknown;
}

const summary: { model: ModelCfg; wall: number; tokens: number; out_path: string }[] = [];

for (const m of MODELS) {
	console.log(`\n=== ${m.key}  (${m.provider}/${m.model}) ===`);
	await deleteChapterMemo(L1_HEADING_ID);

	const t0 = Date.now();
	let run;
	try {
		run = await withRetry(`chapter-collapse ${m.key}`, () =>
			runChapterCollapse(CASE_ID, L1_HEADING_ID, USER_ID, { modelOverride: { provider: m.provider, model: m.model } })
		);
	} catch (err) {
		console.log(`FAILED (${err instanceof Error ? err.message : String(err)}) — continuing`);
		const out = { model: m, error: err instanceof Error ? err.message : String(err), wall_seconds: (Date.now()-t0)/1000 };
		const outPath = `${OUT_DIR}/chapter1-compare-${m.key}.json`;
		writeFileSync(outPath, JSON.stringify(out, null, 2));
		console.log(`  → ${outPath}  (FAILED)`);
		continue;
	}
	const dt = (Date.now() - t0) / 1000;

	if (run.skipped) {
		console.log(`  SKIPPED (existing memo ${run.existingMemoId} — should not happen after delete)`);
		continue;
	}

	const t = run.tokens!;
	console.log(`  ${dt.toFixed(1)}s  in=${t.input} cache_r=${t.cacheRead} out=${t.output}  total=${t.total}`);
	console.log(`  level=L${run.aggregationLevel} mode=${run.inputMode} input=${run.inputCount} units`);
	console.log(`  synthese len: ${run.result!.synthese.length} chars`);
	console.log(`  argumentationswiedergabe len: ${run.result!.argumentationswiedergabe.length} chars`);
	console.log(`  auffaelligkeiten: ${run.result!.auffaelligkeiten.length}`);

	const record: ChapterRecord = {
		model: m,
		wall_seconds: dt,
		tokens: t,
		aggregation_level: run.aggregationLevel!,
		input_mode: run.inputMode!,
		input_count: run.inputCount!,
		result: run.result,
	};
	const outPath = `${OUT_DIR}/chapter1-compare-${m.key}.json`;
	writeFileSync(outPath, JSON.stringify(record, null, 2));
	console.log(`  → ${outPath}`);
	summary.push({ model: m, wall: dt, tokens: t.total, out_path: outPath });
}

// Final cleanup: delete the last model's chapter memo so the DB ends with NO
// chapter-level memo for Chapter 1. To restore the Opus baseline in DB, run
// scripts/run-chapter-collapse.ts (uses ai-settings.json default).
await deleteChapterMemo(L1_HEADING_ID);

console.log('\n=== Summary ===');
for (const s of summary) {
	console.log(`  ${s.model.key.padEnd(20)}  wall ${s.wall.toFixed(1).padStart(6)}s   tokens ${String(s.tokens).padStart(7)}`);
}
console.log('\nFinal chapter memo cleaned up. 7 L3 section memos still in DB.');
console.log('Opus baseline available at docs/experiments/chapter1-opus-collapse.json.');

await pool.end();
